apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    name: myapp-dep
    type: front-end
    app: nginx
    tier: front-end
spec:
    selector:
      matchlabels:
        app: myapp
    replicas: 3
    template:
      metadata:
        name: myapp-nginx
        labels:
          app: myapp-dep
      spec:
        containers:
          - name: nginx-container
            image: nginx