apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-pod
spec:
  template:
    metadata:
      name: myapp-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
replicas: 2